name: Check and Build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Approve build scripts
        run: pnpm approve-builds puppeteer sharp # 将 puppeteer 和 sharp 替换为实际需要批准的包

      - name: Build
        run: pnpm build

      - name: Run linting
        run: pnpm lint && pnpm format:check

      - name: Build
        run: pnpm run build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
